repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      # - id: check-json
      # - id: pretty-format-json
      - id: requirements-txt-fixer

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.790'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy

# -   repo: git://github.com/doublify/pre-commit-isort
#     sha: master
#     hooks:
#     -   id: isort

      # - id: flake8
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: 'v4.3.21'  # Use the revision sha / tag you want to point at
#     hooks:
#     -   id: isort