version: 3
networks:
  web:
    external: true
services:
  twitterstar:
    # build: ./app
    image: mikeryan56/twitterstar:1.0.0
    # image: mikeryan56/twitterstar:latest
    restart: always
    ports:
    - "5000"
    volumes:
    - .:/code


    environment:
    # Application information
    - APP_VERSION='1.0.0'
    #This should be false for production
    - DEBUG=False
    #prd for production or 'dev' for development
    - RELEASE_ENV='dev'
    - SQLALCHEMY_DATABASE_URI='sqlite:///sqlite_db/api.db'
    # postgresql://user:pass@localhost:5432/my_db
    # send grid
    - SENDGRID_API_KEY='insert-key'
    # Loguru settings
    - LOGURU_RETENTION='10 days'
    - LOGURU_ROTATION='100 MB'
    # Values NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
    - LOGURU_LOGGING_LEVEL='INFO'
    #if using traefik
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.twitterstar.rule=Host(`twitterstar.devsetgo.com`)"
    - "traefik.http.routers.twitterstar.entrypoints=websecure"
    - "traefik.http.routers.twitterstar.tls.certresolver=mytlschallenge"
    networks:
      - web

