version: 3
networks:
  web:
    external: true
services:
  devtools:
    # build: ./app
    image: mikeryan56/devtools:1.0.0
    # image: mikeryan56/devtools:latest
    restart: always
    ports:
    - "5000"
    volumes:
    - .:/code

    environment:
    # Application information
    - APP_VERSION='1.0.0'
    #This should be false for production
    - DEBUG=False
    #prd for production or 'dev' for development
    - RELEASE_ENV='dev'
    - SQLALCHEMY_DATABASE_URI='sqlite:///sqlite_db/api.db'
    # postgresql://user:pass@localhost:5432/my_db
    # Loguru settings
    - LOGURU_RETENTION='10 days'
    - LOGURU_ROTATION='100 MB'
    # Values NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
    - LOGURU_LOGGING_LEVEL='INFO'
    # Add Demo Data
    - DEMO_DATA_CREATE=False
    # how many loops of requests
    - DEMO_DATA_LOOPS=0
    #if using traefik
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.devtools.rule=Host(`devtools.devsetgo.com`)"
    - "traefik.http.routers.devtools.entrypoints=websecure"
    - "traefik.http.routers.devtools.tls.certresolver=mytlschallenge"
    networks:
      - web

